angular.module('joj.vendors', [
  //'mm.foundation',
  //'mgcrea.ngStrap.modal',
  //'ngCookies',
  //'ngResource',
  'ui.router',
  'restangular',
  //'angular-jwt',
  //'rzModule',
  //'colorpicker.module',
  //'ipCookie',
  //'ui.select',
  //'ngSanitize',
  //'ngFileUpload',
  'angulartics',
  'angulartics.google.analytics',
  'ngMaterial'
  //'ngAnimate'
]);
